<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<div class="footer">
    <div class="footer_top">
    	<div class="container">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bds_top')->toHtml(); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="footer_mid">
        <div class="container">
            <ul class="footer_menu">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bds_mid')->toHtml(); ?>
            <div class="footer_newsletter"><?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe.phtml')->toHtml(); ?></div>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
    <div class="footer_bottom">
    	<div class="container">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_bds_bottom')->toHtml(); ?>
        </div>
    </div>
</div>
</div>
