<?php
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2011-2014 Webcomm Pty Ltd
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header">
    <div class="container">
        <header role="banner1">
            <div class="logo">
                <?php if ($this->getIsHomePage()):?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php else:?>
                    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php endif?>
            </div>
            <div class="header_right">
                <div class="quick-access">
                    <div class="clearfix">
                        <div class="header_right_top">
                            <ul>
                                <li class="top_links"><?php echo $this->getChildHtml('topLinks') ?></li>
                                <li><?php echo $this->getChildHtml('store_language') ?></li>
                                <li class="header-minicart">
                                    <?php echo $this->getChildHtml('minicart_head'); ?>
                                </li>
                            </ul>
                        </div>
                        <div class="menu">
                            <a class="toggleMenu" href="#"><i aria-hidden="true" class="fa fa-bars"></i></a>
                            <?php echo $this->getChildHtml('topMenu') ?>
                        </div>
                    </div>
                    <?php // echo $this->getChildHtml('topLinks') ?>
                    <?php // echo $this->getChildHtml('topSearch') ?>
                </div>
            </div>
            <?php // echo $this->getChildHtml('topContainer'); ?>
        </header>
    </div>
</div>
